package com.example.warehousetracker.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF1F4E5F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD9EAF0)
val LightOnPrimaryContainer = Color(0xFF062A35)
val LightSecondary = Color(0xFF54717B)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDCE8EC)
val LightOnSecondaryContainer = Color(0xFF112028)
val LightBackground = Color(0xFFF6F8FA)
val LightOnBackground = Color(0xFF14212B)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF14212B)
val LightSurfaceVariant = Color(0xFFEDF3F6)
val LightOnSurfaceVariant = Color(0xFF62707C)
val LightOutline = Color(0xFFD6E0E5)

val DarkPrimary = Color(0xFF8CC2D2)
val DarkOnPrimary = Color(0xFF062A35)
val DarkPrimaryContainer = Color(0xFF173946)
val DarkOnPrimaryContainer = Color(0xFFD9EAF0)
val DarkSecondary = Color(0xFF9DB8C2)
val DarkOnSecondary = Color(0xFF16262D)
val DarkSecondaryContainer = Color(0xFF20353D)
val DarkOnSecondaryContainer = Color(0xFFDCE8EC)
val DarkBackground = Color(0xFF0F171C)
val DarkOnBackground = Color(0xFFE5EDF1)
val DarkSurface = Color(0xFF162127)
val DarkOnSurface = Color(0xFFE5EDF1)
val DarkSurfaceVariant = Color(0xFF1D2B33)
val DarkOnSurfaceVariant = Color(0xFFA8BAC4)
val DarkOutline = Color(0xFF31454F)

val GreenColor = Color(0xFF1F9D68)
val RedColor = Color(0xFFD94B4B)
val AmberColor = Color(0xFFE8A317)
